theme: jekyll-theme-cayman
title:  Algorithmic Biomimimicry 2015 editionn:  
description:  <h1>This website features a 349 page book titled, "Algorithmic Biomimicry", written in 2015 by Royce Milam.  The book provides a method for using a free, opensource program called PocketIFS to create tangible or virtual algorithmic organisms in a 3D virtual machine</h1>
